// Track presets for the in-game picker (index.html). A preset is a ?map= string (see encodeCells in Track.js).
// The Aerodrome Apex circuits come from https://github.com/freaxnx01/game-aerodrome-apex —
// generated by tools/aerodrome-tracks.mjs, do not edit by hand.

export const PRESET_TRACKS = [
	{ id: 'default', name: 'Default', desc: 'The original starter kit circuit', map: null },
	{ id: 'aero', name: 'The Aerodrome', desc: 'Airfield esses, two hairpins, crossing runways', map: 'd4UNeIUBeYUBeoUBe4UBfIUBfYUBfoUBf4UBgIUBgYUBgoUBg4UBhIUBhYUBhoUBh4UBiIUBiYUBioUBi4UHi4QFjIQBjYQHjYMAjYIAjYEAjYAAjX8AjX4EjH4GjH0Ei30Bin0BiX0BiH0GiHwAiHsEh3sBhnsBhXsBhHsBg3sBgnsBgXsBgHsBf3sBfnsBfXsBfHsBe3sBensBeXsBeHsBd3sBdnsFdnwHdXwFdX0AdX4Gdn4Bd34BeH4BeX4Ben4Be34BfH4BfX4Bfn4Bf34BgH4BgX4Bgn4Bg34Eg38Ag4AAg4EAg4IHgoIBgYIBgIIBf4IBfoIBfYIBfIIBe4IBeoIBeYIBeIIBd4IBdoIBdYIBdIIFdIMHc4MBcoMFcoQGc4QBdIQBdYQBdoQEdoUG' },
	{ id: 'northants', name: 'Northants GP', desc: 'Fast, flowing ex-RAF grand prix circuit', map: 'fYYNfoYBf4YBgIYBgYYBgoYBg4YBhIYBhYYBhoYBh4YBiIYHiIUAiIQFiYQBioQHioMAioIAioEAioAAin8Ain4Ain0AinwAinsAinoEiXoBiHoBh3oBhnoBhXoBhHoBg3oBgnoBgXoGgXkEgHkBf3kBfnkBfXkBfHkBe3kBenkBeXkBeHkBd3kFd3oAd3sAd3wAd30Ad34GeH4BeX4Ben4Be34BfH4BfX4Bfn4Bf34BgH4BgX4Bgn4Bg34Eg38Ag4AAg4EAg4IAg4MHgoMBgYMBgIMBf4MBfoMBfYMBfIMBe4MBeoMBeYMBeIMBd4MBdoMBdYMFdYQAdYUGdoUBd4UBeIUBeYUBeoUBe4UBfIUEfIYG' },
	{ id: 'styria', name: 'Styria Ring', desc: 'Short alpine power track — three big stops', map: 'fYYNfoYBf4YBgIYBgYYBgoYBg4YBhIYBhYYBhoYBh4YBiIYBiYYBioYBi4YHi4UAi4QAi4MAi4IAi4EAi4AAi38Ai34Ai30Ai3wAi3sAi3oEinoBiXoBiHoBh3oBhnoGhnkEhXkBhHkBg3kBgnkBgXkBgHkBf3kBfnkBfXkBfHkBe3kBenkBeXkBeHkBd3kFd3oAd3sAd3wAd30Ad34Ad38Ad4AAd4EAd4IAd4MHdoMBdYMBdIMFdIQAdIUAdIYGdYYBdoYBd4YBeIYBeYYBeoYBe4YBfIYB' },
	{ id: 'claypit', name: 'The Claypit', desc: 'Dirt rallycross — three jumps, loose grip', map: 'eIYNeYYBeoYBe4YBfIYBfYYBfoYBf4YBgIYBgYYBgoYBg4YBhIYBhYYBhoYBh4YBiIYBiYYBioYBi4YBjIYHjIUAjIQAjIMAjIIFjYIHjYEAjYAAjX8AjX4EjH4Bi34Gi30Ai3wAi3sEinsGinoAinkEiXkBiHkBh3kBhnkBhXkBhHkBg3kBgnkBgXkBgHkBf3kBfnkBfXkBfHkBe3kBenkBeXkBeHkBd3kBdnkBdXkBdHkFdHoAdHsAdHwAdH0AdH4Hc34Fc38Ac4AAc4EAc4IAc4MAc4QAc4UAc4YGdIYBdYYBdoYBd4YB' },
];
