// Regenerates js/Tracks.js from the circuits of Aerodrome Apex
// (https://github.com/freaxnx01/game-aerodrome-apex).
//
// Usage: node tools/aerodrome-tracks.mjs [url-or-file]
//
// Each circuit is a closed Catmull-Rom spline. It is sampled like the original game does,
// then pushed through the OsmTrack.js raster pipeline (simplify → one-corner raster → pieces).
// Oil, boost pads, jumps and runways have no tile equivalent and are dropped.

import fs from 'node:fs';
import { simplifyPolyline, rasterizeLoop, loopToTrackCells, encodeTrackCells } from '../js/OsmTrack.js';

const SOURCE = process.argv[ 2 ] ?? 'https://github.freaxnx01.ch/game-aerodrome-apex/';
const UNITS_PER_CELL = 100; // road width is 110–130 units, so one tile ≈ one road width
const MODE = 'L';

const html = SOURCE.startsWith( 'http' ) ? await ( await fetch( SOURCE ) ).text() : fs.readFileSync( SOURCE, 'utf8' );
const start = html.indexOf( 'get TRACKS() { return ' );
if ( start < 0 ) throw new Error( 'TRACKS definition not found in ' + SOURCE );
const body = html.slice( start + 'get TRACKS() { return '.length, html.indexOf( 'buildTrack(idx)', start ) );
// Evaluates the TRACKS literal from the page — only point this at a source you trust.
const TRACKS = new Function( 'return ' + body.slice( 0, body.lastIndexOf( ']' ) + 1 ) )();

function catmullRom( p0, p1, p2, p3, t ) {

	const t2 = t * t, t3 = t2 * t;
	return [ 0, 1 ].map( ( k ) => 0.5 * ( ( 2 * p1[ k ] ) + ( - p0[ k ] + p2[ k ] ) * t +
		( 2 * p0[ k ] - 5 * p1[ k ] + 4 * p2[ k ] - p3[ k ] ) * t2 + ( - p0[ k ] + 3 * p1[ k ] - 3 * p2[ k ] + p3[ k ] ) * t3 ) );

}

const presets = [];

for ( const def of TRACKS ) {

	const c = def.ctrl, n = c.length, pts = [];

	for ( let i = 0; i < n; i ++ ) {

		const p0 = c[ ( i - 1 + n ) % n ], p1 = c[ i ], p2 = c[ ( i + 1 ) % n ], p3 = c[ ( i + 2 ) % n ];
		const steps = Math.max( 3, Math.round( Math.hypot( p2[ 0 ] - p1[ 0 ], p2[ 1 ] - p1[ 1 ] ) / 7 ) );
		for ( let s = 0; s < steps; s ++ ) {

			const [ x, y ] = catmullRom( p0, p1, p2, p3, s / steps );
			pts.push( { x, y: - y } ); // canvas y points down; the raster expects y = north

		}

	}

	const simplified = simplifyPolyline( [ ...pts, pts[ 0 ] ], UNITS_PER_CELL ).slice( 0, - 1 );
	const { cells, duplicates, shortcuts } = rasterizeLoop( simplified, UNITS_PER_CELL, MODE );
	if ( duplicates.size || shortcuts ) throw new Error( `${ def.name }: raster collided with itself` );

	const name = def.name.toLowerCase().replace( /(^|\s)\S/g, ( s ) => s.toUpperCase() ).replace( /\bGp\b/, 'GP' );
	presets.push( { id: def.id, name, desc: def.desc, map: encodeTrackCells( loopToTrackCells( cells ) ) } );
	console.log( `${ name }: ${ cells.length } cells` );

}

const out = `// Track presets for the in-game picker (index.html). A preset is a ?map= string (see encodeCells in Track.js).
// The Aerodrome Apex circuits come from https://github.com/freaxnx01/game-aerodrome-apex —
// generated by tools/aerodrome-tracks.mjs, do not edit by hand.

export const PRESET_TRACKS = [
	{ id: 'default', name: 'Default', desc: 'The original starter kit circuit', map: null },
${ presets.map( ( p ) => `\t{ id: '${ p.id }', name: '${ p.name }', desc: '${ p.desc.replace( /'/g, "\\'" ) }', map: '${ p.map }' },` ).join( '\n' ) }
];
`;

fs.writeFileSync( new URL( '../js/Tracks.js', import.meta.url ), out );
