// Bakes the OpenStreetMap preset tracks into js/OsmPresets.js.
//
// Usage: node tools/osm-presets.mjs           bake from the committed fixtures in test/fixtures/
//        node tools/osm-presets.mjs --fetch   refresh those fixtures from Overpass first
//
// A preset is a waypoint loop over real streets — the same pipeline as osm-track.html's point
// mode (bakeLoop in OsmTrack.js). The fixture keeps only the preset's roads, so baking is
// deterministic and test/osm-presets.test.mjs checks the committed tiles still match it.

import fs from 'node:fs';
import { fileURLToPath } from 'node:url';
import { overpassQuery, fetchOverpass, bakeLoop, encodeTrackCells } from '../js/OsmTrack.js';
import { encodeOsmParam } from '../js/OsmData.js';

export const PRESET_DEFS = [
	{
		id: 'bad-saeckingen',
		name: 'Bad Säckingen Altstadt',
		desc: 'Old-town lanes and the covered wooden bridge over the Rhine',
		fixture: 'bad-saeckingen.json',
		bbox: [ 47.5435, 7.9400, 47.5565, 7.9560 ],
		// + pedestrian: old-town lanes and the Holzbrücke; + path: the bridge's two stubs on the Swiss side
		highways: 'primary|secondary|tertiary|unclassified|residential|living_street|service|track|pedestrian|path',
		waypoints: [
			[ 47.55152, 7.95004 ], // Holzbrücke, German end — start/finish
			[ 47.55134, 7.95276 ], // Holzbrücke, Swiss end (Stein AG)
			[ 47.54606, 7.94972 ], // Fridolinsbrücke
			[ 47.5515, 7.94551 ], // Hauensteinstraße
			[ 47.55332, 7.94844 ], // Steinbrückstraße
		],
		mpc: 10,
		mode: 'auto',
	},
];

const KEEP_TAGS = [ 'highway', 'name', 'bridge:name', 'area' ];

const fixtureUrl = ( def ) => new URL( '../test/fixtures/' + def.fixture, import.meta.url );

export function readFixture( def ) {

	return JSON.parse( fs.readFileSync( fixtureUrl( def ) ) );

}

// Preset definition + OSM → { id, name, desc, map, osm, ids, cells }. A preset must follow its
// streets completely, so a route that repeats a street or a loop that touches itself is an error.
export function bakePreset( def, osm ) {

	const r = bakeLoop( osm, def );

	if ( new Set( r.ids ).size !== r.ids.length ) throw new Error( `${ def.name }: the route drives a street twice — move a waypoint` );

	if ( r.shortcuts || r.duplicates.size ) {

		throw new Error( `${ def.name }: the loop touches itself (${ r.shortcuts } shortcuts, ${ r.duplicates.size } cells twice) — move a waypoint` );

	}

	return {
		id: def.id,
		name: def.name,
		desc: def.desc,
		map: encodeTrackCells( r.cells ),
		osm: encodeOsmParam( { bbox: def.bbox, mpc: def.mpc, offX: r.center.offX, offZ: r.center.offZ } ),
		ids: r.ids,
		cells: r.cells,
	};

}

export function presetsModule( presets ) {

	const rows = presets.map( ( p ) => `\t{ id: '${ p.id }', name: '${ p.name }', desc: '${ p.desc.replace( /'/g, "\\'" ) }', map: '${ p.map }', osm: '${ p.osm }' },` );

	return `// OpenStreetMap preset tracks for the in-game picker, with their &osm= surroundings.
// Generated by tools/osm-presets.mjs from test/fixtures/ — do not edit by hand.

export const OSM_PRESETS = [
${ rows.join( '\n' ) }
];
`;

}

async function fetchFixture( def ) {

	const { osm, source } = await fetchOverpass( overpassQuery( def.bbox, def.highways ), { storage: null } );

	const elements = osm.elements.map( ( el ) => el.type === 'node'
		? { type: 'node', id: el.id, lat: + el.lat.toFixed( 7 ), lon: + el.lon.toFixed( 7 ) }
		: { type: 'way', id: el.id, nodes: el.nodes, tags: Object.fromEntries( KEEP_TAGS.filter( ( k ) => el.tags?.[ k ] ).map( ( k ) => [ k, el.tags[ k ] ] ) ) } );

	fs.writeFileSync( fixtureUrl( def ), JSON.stringify( { bbox: def.bbox, elements } ) );
	console.log( `${ def.fixture }: ${ elements.length } elements from ${ source }` );

}

if ( process.argv[ 1 ] === fileURLToPath( import.meta.url ) ) {

	if ( process.argv.includes( '--fetch' ) ) for ( const def of PRESET_DEFS ) await fetchFixture( def );

	const presets = PRESET_DEFS.map( ( def ) => bakePreset( def, readFixture( def ) ) );
	fs.writeFileSync( new URL( '../js/OsmPresets.js', import.meta.url ), presetsModule( presets ) );
	for ( const p of presets ) console.log( `${ p.name }: ${ p.cells.length } cells` );

}
